baseurl = "/"
languageCode = "en-us"
title = "Fang|放"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "中文"
    url = "/cn/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    

[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn]]
    name = "博客"
    url = "/cn/"
    weight = 3
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 4

[params]
  description = "A notebook of Fang."
  footer = "&copy; [Fang](me.fangbucks.com) 2018 | [Fangbucks](http://www.fangbucks.com/) | [Twitter](https://twitter.com/funfunchen)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

